In [2]:
import polars as pl
pl.Config.set_tbl_rows(30)

polars.config.Config

In [3]:
df = pl.read_csv("results.csv")

In [4]:
(
    df
    .filter(pl.col("split").eq("val"))
    .group_by("method", "model_version", "reasoning", "effort")
    .agg(
        pl.col("correct_square_mean").mean(),
        pl.col("correct_board_mean").mean(),
        pl.len().alias("n")
    )
    .sort("correct_board_mean", descending=True)
    .filter(pl.col("method").eq("cnn"))
)

shape: (7, 7)
┌────────┬────────────────────┬───────────┬────────┬────────────────────┬────────────────────┬─────┐
│ method ┆ model_version      ┆ reasoning ┆ effort ┆ correct_square_mea ┆ correct_board_mean ┆ n   │
│ ---    ┆ ---                ┆ ---       ┆ ---    ┆ n                  ┆ ---                ┆ --- │
│ str    ┆ str                ┆ str       ┆ str    ┆ ---                ┆ f64                ┆ u32 │
│        ┆                    ┆           ┆        ┆ f64                ┆                    ┆     │
╞════════╪════════════════════╪═══════════╪════════╪════════════════════╪════════════════════╪═════╡
│ cnn    ┆ optimised_plus_pri ┆ none      ┆ high   ┆ 0.739553           ┆ 0.947831           ┆ 5   │
│        ┆ or_correctio…      ┆           ┆        ┆                    ┆                    ┆     │
│ cnn    ┆ optimised          ┆ none      ┆ high   ┆ 0.727543           ┆ 0.910303           ┆ 5   │
│ cnn    ┆ optimised_10k      ┆ none      ┆ high   ┆ 0.708313           ┆ 0.909649           ┆ 5   │
│ cnn    ┆ square_global      ┆ none      ┆ high   ┆ 0.716104           ┆ 0.859952           ┆ 5   │
│ cnn    ┆ square_per_square  ┆ none      ┆ high   ┆ 0.759768           ┆ 0.858538           ┆ 5   │
│ cnn    ┆ optimised_5k       ┆ none      ┆ high   ┆ 0.63859            ┆ 0.788188           ┆ 5   │
│ cnn    ┆ none_global        ┆ none      ┆ high   ┆ 0.602451           ┆ 0.307201           ┆ 5   │
└────────┴────────────────────┴───────────┴────────┴────────────────────┴────────────────────┴─────┘

In [5]:
(
    df.filter(
        pl.col("model_version").str.starts_with("optimised"), 
        ~pl.col("model_version").str.contains("prior"),
        pl.col("split").eq("val")
    )
    .group_by("method", "model_version")
    .agg(
        pl.col("correct_square_mean").mean(),
        pl.col("correct_board_mean").mean()
    )
    .select(
        pl.col("method").replace_strict({"cnn": "CNN"}).alias("model type"),
        pl.col("model_version").replace_strict({"optimised": 13184, "optimised_10k": 9538, "optimised_5k": 4864}).alias("n"),
        pl.col("correct_square_mean").round(3).alias("square accuracy"),
        pl.col("correct_board_mean").round(3).alias("move accuracy")
    )
).write_csv("results_data_ablation.csv")

In [6]:
df.filter(pl.col("method").eq("cnn")).unique(["model_version"])

shape: (7, 30)
┌────────┬─────────────┬────────────┬───────────┬───┬───────────┬────────────┬────────────┬────────┐
│ method ┆ model_versi ┆ prompt_ver ┆ reasoning ┆ … ┆ cost_mean ┆ n_suggeste ┆ n_suggeste ┆ effort │
│ ---    ┆ on          ┆ sion       ┆ ---       ┆   ┆ ---       ┆ d          ┆ d_mean     ┆ ---    │
│ str    ┆ ---         ┆ ---        ┆ str       ┆   ┆ f64       ┆ ---        ┆ ---        ┆ str    │
│        ┆ str         ┆ i64        ┆           ┆   ┆           ┆ str        ┆ str        ┆        │
╞════════╪═════════════╪════════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪════════╡
│ cnn    ┆ optimised_5 ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
│        ┆ k           ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ cnn    ┆ none_global ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
│ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
│        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ cnn    ┆ square_glob ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
│        ┆ al          ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ cnn    ┆ optimised_1 ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
│        ┆ 0k          ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ cnn    ┆ square_per_ ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
│        ┆ square      ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ cnn    ┆ optimised   ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
└────────┴─────────────┴────────────┴───────────┴───┴───────────┴────────────┴────────────┴────────┘

In [7]:
df.filter(pl.col("model_version").eq("none_global"), pl.col("split").eq("val"))["correct_board_mean"].mean()

0.3072014260249555

In [8]:
# Evaluate effectiveness of mask;
# Baseline: none_global;
# square_global
# optimised
(
    df.filter(
        pl.col("model_version").is_in(["none_global", "square_global", "optimised"]),
        pl.col("split").eq("val")
    )
    .group_by("method", "model_version")
    .agg(
        pl.col("correct_square_mean").mean(),
        pl.col("correct_board_mean").mean()
    )
    .select(
        pl.col("method").replace_strict({"cnn": "CNN"}).alias("model type"),
        pl.col("model_version").replace_strict({"none_global": "no masks, global padding", "square_global": "square mask, global padding", "optimised": "full mask, square-dependent padding"}),
        pl.col("correct_square_mean").round(3).alias("square accuracy"),
        pl.col("correct_board_mean").round(3).alias("move accuracy")
    )
).write_csv("results_geometric_ablation.csv")

In [9]:
model_version_map = {
    "claude-opus-5": "Opus 5",
    "claude-sonnet-5": "Sonnet 5"
}

reasoning_enabled_map = {
    "thinking": "yes",
    "none": "no"
}




(
    df
    .filter(pl.col("split").eq("val"))
    .group_by("method", "model_version", "reasoning", "effort")
    .agg(
        pl.col("correct_square_mean").mean(),
        pl.col("correct_board_mean").mean(),
        pl.len().alias("n")
    )
    .sort("correct_board_mean", descending=True)
    .group_by("method", "model_version", "reasoning")
    .agg(
        pl.col("correct_square_mean").first(),
        pl.col("correct_board_mean").first(),
        pl.col("effort").first()
    )
    .filter(~pl.col("method").is_in(["cnn", "fen_whole"]), pl.col("model_version").ne("claude-opus-4-8"))
    .select(
        pl.col("model_version").replace_strict(model_version_map).alias("model version"),
        pl.col("method").str.starts_with("square").replace_strict({True: "yes", False: "no"}).alias("classify squares first?"),
        pl.col("method").alias("prompt version"),
        pl.when(pl.col("reasoning").eq("thinking"))
        .then(pl.col("effort").replace_strict({"low": "yes (low effort)", "medium": "yes (medium effort)", "high": "yes (high effort)"}))
        .otherwise(pl.lit("no"))
        .alias("reasoning enabled?"),
        pl.col("correct_board_mean").alias("move accuracy"),
        pl.col("correct_square_mean").alias("square accuracy")
    )
    .with_columns(
        pl.when(pl.col("classify squares first?").eq("no"))
        .then(pl.lit(None))
        .otherwise(pl.col("square accuracy"))
        .alias("square accuracy")
    )
).write_csv("claude_results.csv")

# How to turn this into an actual table I can show in the blog post?
# Columns need to be renamed 
    # reasoning -> Reasoning enabled?
    # correct_square_mean -> Square Accuracy
    # correct_board_mean -> Move Accuracy
# Values need to be renamed:
    # claude-opus-5 -> Opus 5
    # correct

In [10]:
df.filter(pl.col("model_version").eq("claude-opus-5"), pl.col("split").eq("test"))

shape: (11, 30)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ method     ┆ model_vers ┆ prompt_ve ┆ reasoning ┆ … ┆ cost_mean ┆ n_suggest ┆ n_suggest ┆ effort │
│ ---        ┆ ion        ┆ rsion     ┆ ---       ┆   ┆ ---       ┆ ed        ┆ ed_mean   ┆ ---    │
│ str        ┆ ---        ┆ ---       ┆ str       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ str    │
│            ┆ str        ┆ i64       ┆           ┆   ┆           ┆ str       ┆ str       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.202691  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.202756  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.199876  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.2032475 ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.203038  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.201617  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.204188  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.203465  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.209023  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null]     ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.206376  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null]     ┆           ┆        │
│ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.205286  ┆ [null,    ┆ null      ┆ low    │
│ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
│            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [11]:
import os
os.getcwd()

'c:\\Users\\User\\Documents\\Coding\\robot-chess-commentator\\evaluation'

In [12]:
df.filter(pl.col("model_version").eq("claude-sonnet-5"), pl.col("method").eq("board")).select("reasoning", "correct_square", "correct_square_mean", "correct_board", "correct_board_mean", "board_rank", "n_suggested", "none_legal", "first_output_illegal", "n_suggested_mean"),

(shape: (10, 10)
 ┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
 │ reasoning ┆ correct_s ┆ correct_s ┆ correct_b ┆ … ┆ n_suggest ┆ none_lega ┆ first_out ┆ n_sugges │
 │ ---       ┆ quare     ┆ quare_mea ┆ oard      ┆   ┆ ed        ┆ l         ┆ put_illeg ┆ ted_mean │
 │ str       ┆ ---       ┆ n         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ al        ┆ ---      │
 │           ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
 │           ┆           ┆ f64       ┆           ┆   ┆           ┆           ┆ str       ┆          │
 ╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
 │ none      ┆ [0.9375,  ┆ 0.944444  ┆ [false,   ┆ … ┆ [1, 1, 1, ┆ [false,   ┆ [false,   ┆ 1.222222 │
 │           ┆ 0.953125, ┆           ┆ false,    ┆   ┆ 1, 1, 1,  ┆ true,     ┆ true,     ┆ 22222222 │
 │           ┆ 0.9375,   ┆           ┆ false,    ┆   ┆ 1, 1, 1,  ┆ true,     ┆ true,     ┆ 23       │
 │           ┆ 0.9…      ┆           ┆ false, f… ┆   ┆ 2,…       ┆ true,     ┆ true,     ┆          │
 │           ┆           ┆           ┆           ┆   ┆           ┆ true…     ┆ true…     ┆          │
 │ none      ┆ [0.921875 ┆ 0.9375    ┆ [false,   ┆ … ┆ [1, 1, 1, ┆ [true,    ┆ [true,    ┆ 1.117647 │
 │           ┆ ,         ┆           ┆ false,    ┆   ┆ 1, 1, 1,  ┆ true,     ┆ true,     ┆ 05882352 │
 │           ┆ 0.90625,  ┆           ┆ false,    ┆   ┆ 2, 1, 1,  ┆ true,     ┆ true,     ┆ 94       │
 │           ┆ 0.9375,   ┆           ┆ false, f… ┆   ┆ 1,…       ┆ false,    ┆ false,    ┆          │
 │           ┆ 0.…       ┆           ┆           ┆   ┆           ┆ true…     ┆ true…     ┆          │
 │ none      ┆ [0.96875, ┆ 0.940341  ┆ [false,   ┆ … ┆ [1, 1, 2, ┆ [true,    ┆ [true,    ┆ 1.181818 │
 │           ┆ 0.953125, ┆           ┆ false,    ┆   ┆ 1, 2, 1,  ┆ false,    ┆ false,    ┆ 18181818 │
 │           ┆ 0.921875, ┆           ┆ false,    ┆   ┆ 1, 1, 1,  ┆ true,     ┆ true,     ┆ 19       │
 │           ┆ …         ┆           ┆ false, f… ┆   ┆ 1,…       ┆ false,    ┆ false,    ┆          │
 │           ┆           ┆           ┆           ┆   ┆           ┆ tru…      ┆ tru…      ┆          │
 │ none      ┆ [0.96875, ┆ 0.958333  ┆ [false,   ┆ … ┆ [1, 1, 1, ┆ [true,    ┆ [true,    ┆ 1.2      │
 │           ┆ 0.96875,  ┆           ┆ false,    ┆   ┆ 2, 1, 1,  ┆ true,     ┆ true,     ┆          │
 │           ┆ 0.96875,  ┆           ┆ false,    ┆   ┆ 1, 1, 1,  ┆ true,     ┆ true,     ┆          │
 │           ┆ 0.…       ┆           ┆ false, f… ┆   ┆ 2]        ┆ true,     ┆ true,     ┆          │
 │           ┆           ┆           ┆           ┆   ┆           ┆ true,…    ┆ true,…    ┆          │
 │ none      ┆ [0.96875, ┆ 0.950521  ┆ [false,   ┆ … ┆ [1, 1, 1, ┆ [true,    ┆ [true,    ┆ 1.333333 │
 │           ┆ 0.9375,   ┆           ┆ false,    ┆   ┆ 2, 1, 2,  ┆ true,     ┆ true,     ┆ 33333333 │
 │           ┆ 1.0,      ┆           ┆ true,     ┆   ┆ 1, 1, 1,  ┆ false,    ┆ false,    ┆ 33       │
 │           ┆ 0.9375,…  ┆           ┆ false,    ┆   ┆ 2,…       ┆ false,    ┆ false,    ┆          │
 │           ┆           ┆           ┆ fa…       ┆   ┆           ┆ tru…      ┆ tru…      ┆          │
 │ thinking  ┆ [1.0,     ┆ 0.940625  ┆ [true,    ┆ … ┆ [2, 0, 1, ┆ [false,   ┆ [false,   ┆ 0.888888 │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 1, 1, 3,  ┆ true,     ┆ true,     ┆ 88888888 │
 │           ┆ 0.9375,   ┆           ┆ false,    ┆   ┆ 1, 1, 2,  ┆ false,    ┆ false,    ┆ 88       │
 │           ┆ 0.9375,   ┆           ┆ false,    ┆   ┆ 0,…       ┆ false,    ┆ false,    ┆          │
 │           ┆ 0.…       ┆           ┆ fa…       ┆   ┆           ┆ tr…       ┆ tr…       ┆          │
 │ thinking  ┆ [0.96875, ┆ 0.953125  ┆ [true,    ┆ … ┆ [1, 1, 0, ┆ [false,   ┆ [false,   ┆ 0.117647 │
 │           ┆ 0.9375,   ┆           ┆ false,    ┆   ┆ 0, 0, 0,  ┆ true,     ┆ true,     ┆ 05882352 │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 0, 0, 0,  ┆ true,     ┆ true,     ┆ 941      │
 │           ┆ null, …   ┆           ┆ false,    ┆   ┆ 0,…       ┆ true,     ┆ true,     ┆          │
 │           ┆           ┆           ┆ fa…       ┆   ┆           ┆ true…     ┆ true…     ┆          │
 │ thinking  ┆ [0.9375,  ┆ 0.9375    ┆ [false,   ┆ … ┆ [2, 0, 0, ┆ [false,   ┆ [false,   ┆ 0.181818 │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 0, 0, 0,  ┆ true,     ┆ true,     ┆ 18181818 │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 0, 0, 0,  ┆ true,     ┆ true,     ┆ 182      │
 │           ┆ null,     ┆           ┆ false, f… ┆   ┆ 0,…       ┆ true,     ┆ true,     ┆          │
 │           ┆ nul…      ┆           ┆           ┆   ┆           ┆ true…     ┆ true…     ┆          │
 │ thinking  ┆ [null,    ┆ null      ┆ [false,   ┆ … ┆ [0, 0, 0, ┆ [true,    ┆ [true,    ┆ 0.0      │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 0, 0, 0,  ┆ true,     ┆ true,     ┆          │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 0, 0, 0,  ┆ true,     ┆ true,     ┆          │
 │           ┆ null,     ┆           ┆ false, f… ┆   ┆ 0]        ┆ true,     ┆ true,     ┆          │
 │           ┆ null,…    ┆           ┆           ┆   ┆           ┆ true,…    ┆ true,…    ┆          │
 │ thinking  ┆ [null,    ┆ 0.958807  ┆ [false,   ┆ … ┆ [0, 0, 1, ┆ [true,    ┆ [true,    ┆ 0.666666 │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 0, 0, 1,  ┆ true,     ┆ true,     ┆ 66666666 │
 │           ┆ 1.0,      ┆           ┆ true,     ┆   ┆ 1, 1, 1,  ┆ false,    ┆ false,    ┆ 66       │
 │           ┆ null,     ┆           ┆ false,    ┆   ┆ 1,…       ┆ true,     ┆ true,     ┆          │
 │           ┆ null, …   ┆           ┆ fa…       ┆   ┆           ┆ true…     ┆ true…     ┆          │
 └───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘,)

In [13]:
df.columns

['method',
 'model_version',
 'prompt_version',
 'reasoning',
 'prior_correction',
 'data_path',
 'split',
 'setup_id',
 'n_boards',
 'correct_square',
 'correct_square_mean',
 'correct_board',
 'correct_board_mean',
 'board_rank',
 'board_rank_mean',
 'first_output_illegal',
 'first_output_illegal_mean',
 'none_legal',
 'none_legal_mean',
 'input_tokens',
 'input_tokens_mean',
 'output_tokens',
 'output_tokens_mean',
 'inference_time',
 'inference_time_mean',
 'cost',
 'cost_mean',
 'n_suggested',
 'n_suggested_mean',
 'effort']

In [14]:
df["method"].unique()

shape: (6,)
Series: 'method' [str]
[
	"cnn"
	"square_logits"
	"board"
	"fen_whole"
	"square_label"
	"move"
]

In [15]:
(
    df.filter(pl.col("split").eq("test"), pl.col("model_version").str.contains("claude"))
    .group_by("method", "model_version", "reasoning", "effort")
    .agg(
        pl.col("correct_board_mean").mean()
    )
    .sort("correct_board_mean", descending=True)
)

shape: (1, 5)
┌───────────────┬───────────────┬───────────┬────────┬────────────────────┐
│ method        ┆ model_version ┆ reasoning ┆ effort ┆ correct_board_mean │
│ ---           ┆ ---           ┆ ---       ┆ ---    ┆ ---                │
│ str           ┆ str           ┆ str       ┆ str    ┆ f64                │
╞═══════════════╪═══════════════╪═══════════╪════════╪════════════════════╡
│ square_logits ┆ claude-opus-5 ┆ thinking  ┆ low    ┆ 0.226659           │
└───────────────┴───────────────┴───────────┴────────┴────────────────────┘

In [16]:
(
    df.filter(pl.col("method").eq("square_logits"))
    .select("n_boards", "correct_square_mean", "correct_board_mean", "board_rank", "model_version")
)

shape: (41, 5)
┌──────────┬─────────────────────┬────────────────────┬──────────────────────────┬─────────────────┐
│ n_boards ┆ correct_square_mean ┆ correct_board_mean ┆ board_rank               ┆ model_version   │
│ ---      ┆ ---                 ┆ ---                ┆ ---                      ┆ ---             │
│ i64      ┆ f64                 ┆ f64                ┆ str                      ┆ str             │
╞══════════╪═════════════════════╪════════════════════╪══════════════════════════╪═════════════════╡
│ 18       ┆ 0.228299            ┆ 0.0                ┆ [0.6666666666666667,     ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 0.8, 0.71…               ┆                 │
│ 18       ┆ 0.215278            ┆ 0.111111           ┆ [0.7142857142857143,     ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 0.65, 1.0…               ┆                 │
│ 17       ┆ 0.205882            ┆ 0.0                ┆ [0.8666666666666667,     ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 0.6428571…               ┆                 │
│ 11       ┆ 0.268466            ┆ 0.090909           ┆ [0.32352941176470584,    ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 0.555555…                ┆                 │
│ 10       ┆ 0.2515625           ┆ 0.1                ┆ [0.45238095238095233,    ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 0.354838…                ┆                 │
│ 18       ┆ 0.159722            ┆ 0.333333           ┆ [0.5384615384615384,     ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 1.0, null…               ┆                 │
│ 17       ┆ 0.215074            ┆ 0.058824           ┆ [0.9333333333333333,     ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 1.0, 0.71…               ┆                 │
│ 11       ┆ 0.296875            ┆ 0.090909           ┆ [0.4117647058823529,     ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 0.3888888…               ┆                 │
│ 10       ┆ 0.2671875           ┆ 0.1                ┆ [0.26190476190476186,    ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 0.451612…                ┆                 │
│ 18       ┆ 0.192708            ┆ 0.166667           ┆ [0.9230769230769231,     ┆ claude-sonnet-5 │
│          ┆                     ┆                    ┆ 1.0, null…               ┆                 │
│ 18       ┆ 0.368056            ┆ 0.166667           ┆ [0.9047619047619048,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 1.0, 0.95…               ┆                 │
│ 17       ┆ 0.415441            ┆ 0.470588           ┆ [0.9666666666666667,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9285714…               ┆                 │
│ 11       ┆ 0.458807            ┆ 0.181818           ┆ [0.9705882352941176,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9722222…               ┆                 │
│ 10       ┆ 0.434375            ┆ 0.3                ┆ [0.7142857142857143,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 1.0, 0.90…               ┆                 │
│ 18       ┆ 0.449653            ┆ 0.277778           ┆ [1.0, 1.0, null,         ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.82926829268…           ┆                 │
│ …        ┆ …                   ┆ …                  ┆ …                        ┆ …               │
│ 17       ┆ 0.474265            ┆ 0.470588           ┆ [0.9666666666666667,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9285714…               ┆                 │
│ 11       ┆ 0.548295            ┆ 0.363636           ┆ [1.0,                    ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.6944444444444444,      ┆                 │
│          ┆                     ┆                    ┆ 0.88…                    ┆                 │
│ 10       ┆ 0.5375              ┆ 0.3                ┆ [0.5238095238095238,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 1.0, 0.95…               ┆                 │
│ 18       ┆ 0.552083            ┆ 0.333333           ┆ [0.8974358974358975,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 1.0, null…               ┆                 │
│ 7        ┆ 0.448661            ┆ 0.285714           ┆ [1.0, 1.0,               ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.43333333333333335…     ┆                 │
│ 9        ┆ 0.458333            ┆ 0.111111           ┆ [0.5588235294117647,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.875, 0.…               ┆                 │
│ 8        ┆ 0.542969            ┆ 0.375              ┆ [1.0,                    ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9411764705882353,      ┆                 │
│          ┆                     ┆                    ┆ 0.97…                    ┆                 │
│ 7        ┆ 0.439732            ┆ 0.142857           ┆ [1.0, 0.875,             ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.928571428571428…       ┆                 │
│ 6        ┆ 0.46875             ┆ 0.0                ┆ [0.972972972972973,      ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.75, 0.53…              ┆                 │
│ 7        ┆ 0.495536            ┆ 0.0                ┆ [0.8409090909090909,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9555555…               ┆                 │
│ 7        ┆ 0.506696            ┆ 0.142857           ┆ [0.6590909090909092,     ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 1.0, 0.82…               ┆                 │
│ 7        ┆ 0.515625            ┆ 0.285714           ┆ [1.0,                    ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9803921568627451,      ┆                 │
│          ┆                     ┆                    ┆ 0.60…                    ┆                 │
│ 5        ┆ 0.378125            ┆ 0.4                ┆ [1.0,                    ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9722222222222222,      ┆                 │
│          ┆                     ┆                    ┆ 0.80…                    ┆                 │
│ 4        ┆ 0.546875            ┆ 0.5                ┆ [1.0,                    ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.8536585365853658,      ┆                 │
│          ┆                     ┆                    ┆ 1.0,…                    ┆                 │
│ 8        ┆ 0.560547            ┆ 0.25               ┆ [1.0,                    ┆ claude-opus-5   │
│          ┆                     ┆                    ┆ 0.9736842105263158,      ┆                 │
│          ┆                     ┆                    ┆ 0.97…                    ┆                 │
└──────────┴─────────────────────┴────────────────────┴──────────────────────────┴─────────────────┘

In [17]:
df.filter(pl.col("method").eq("move"))

shape: (15, 30)
┌────────┬─────────────┬────────────┬───────────┬───┬───────────┬────────────┬────────────┬────────┐
│ method ┆ model_versi ┆ prompt_ver ┆ reasoning ┆ … ┆ cost_mean ┆ n_suggeste ┆ n_suggeste ┆ effort │
│ ---    ┆ on          ┆ sion       ┆ ---       ┆   ┆ ---       ┆ d          ┆ d_mean     ┆ ---    │
│ str    ┆ ---         ┆ ---        ┆ str       ┆   ┆ f64       ┆ ---        ┆ ---        ┆ str    │
│        ┆ str         ┆ i64        ┆           ┆   ┆           ┆ str        ┆ str        ┆        │
╞════════╪═════════════╪════════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪════════╡
│ move   ┆ claude-opus ┆ 1          ┆ none      ┆ … ┆ 0.00622   ┆ null       ┆ null       ┆ high   │
│        ┆ -4-8        ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ move   ┆ claude-opus ┆ 1          ┆ none      ┆ … ┆ 0.006805  ┆ null       ┆ null       ┆ high   │
│        ┆ -4-8        ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ move   ┆ claude-opus ┆ 1          ┆ none      ┆ … ┆ 0.006439  ┆ null       ┆ null       ┆ high   │
│        ┆ -4-8        ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ move   ┆ claude-opus ┆ 1          ┆ none      ┆ … ┆ 0.006912  ┆ null       ┆ null       ┆ high   │
│        ┆ -4-8        ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ move   ┆ claude-opus ┆ 1          ┆ none      ┆ … ┆ 0.006505  ┆ null       ┆ null       ┆ high   │
│        ┆ -4-8        ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ none      ┆ … ┆ 0.016934  ┆ [0, 1, 1,  ┆ 0.16666666 ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆ 666666666  ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 1, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0,…        ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ none      ┆ … ┆ 0.018176  ┆ [1, 0, 0,  ┆ 0.11764705 ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆ 882352941  ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0,…        ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ none      ┆ … ┆ 0.018912  ┆ [0, 0, 0,  ┆ 0.0        ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0,…        ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ none      ┆ … ┆ 0.0189444 ┆ [0, 0, 0,  ┆ 0.0        ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0]         ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ none      ┆ … ┆ 0.001862  ┆ [1, 1, 1,  ┆ 1.0        ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 1, 1, 1,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 1, 1, 1,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 1,…        ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ thinking  ┆ … ┆ 0.044707  ┆ [1, 1, 1,  ┆ 0.61111111 ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 0, 1, 1,   ┆ 11111112   ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 1, 1, 3,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0,…        ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ thinking  ┆ … ┆ 0.055153  ┆ [1, 1, 1,  ┆ 0.23529411 ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 0, 0, 1,   ┆ 764705882  ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0,…        ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ thinking  ┆ … ┆ 0.050864  ┆ [1, 0, 1,  ┆ 0.54545454 ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 1, 1, 0,   ┆ 54545454   ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 2,…        ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ thinking  ┆ … ┆ 0.062698  ┆ [0, 0, 1,  ┆ 0.4        ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 3, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0]         ┆            ┆        │
│ move   ┆ claude-sonn ┆ 1          ┆ thinking  ┆ … ┆ 0.051176  ┆ [0, 0, 1,  ┆ 0.38888888 ┆ high   │
│        ┆ et-5        ┆            ┆           ┆   ┆           ┆ 0, 0, 0,   ┆ 88888889   ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0, 0, 1,   ┆            ┆        │
│        ┆             ┆            ┆           ┆   ┆           ┆ 0,…        ┆            ┆        │
└────────┴─────────────┴────────────┴───────────┴───┴───────────┴────────────┴────────────┴────────┘

In [18]:
df.group_by(["method", "model_version"]).agg(pl.col("correct_board_mean").mean(), pl.col("none_legal").mean(), pl.len().alias("n_setups"))

shape: (15, 5)
┌───────────────┬─────────────────────────────────┬────────────────────┬────────────┬──────────┐
│ method        ┆ model_version                   ┆ correct_board_mean ┆ none_legal ┆ n_setups │
│ ---           ┆ ---                             ┆ ---                ┆ ---        ┆ ---      │
│ str           ┆ str                             ┆ f64                ┆ str        ┆ u32      │
╞═══════════════╪═════════════════════════════════╪════════════════════╪════════════╪══════════╡
│ square_label  ┆ claude-sonnet-5                 ┆ 0.128705           ┆ null       ┆ 10       │
│ cnn           ┆ none_global                     ┆ 0.478962           ┆ null       ┆ 16       │
│ cnn           ┆ optimised_plus_prior_correctio… ┆ 0.946495           ┆ null       ┆ 16       │
│ cnn           ┆ optimised                       ┆ 0.945928           ┆ null       ┆ 16       │
│ cnn           ┆ square_global                   ┆ 0.913824           ┆ null       ┆ 16       │
│ cnn           ┆ square_per_square               ┆ 0.894905           ┆ null       ┆ 16       │
│ fen_whole     ┆ claude-sonnet-5                 ┆ 0.0                ┆ null       ┆ 5        │
│ board         ┆ claude-sonnet-5                 ┆ 0.03366            ┆ null       ┆ 10       │
│ square_logits ┆ claude-sonnet-5                 ┆ 0.105175           ┆ null       ┆ 10       │
│ cnn           ┆ optimised_10k                   ┆ 0.88062            ┆ null       ┆ 16       │
│ move          ┆ claude-sonnet-5                 ┆ 0.039542           ┆ null       ┆ 10       │
│ cnn           ┆ optimised_5k                    ┆ 0.691373           ┆ null       ┆ 16       │
│ move          ┆ claude-opus-4-8                 ┆ 0.045098           ┆ null       ┆ 5        │
│ square_label  ┆ claude-opus-5                   ┆ 0.181165           ┆ null       ┆ 15       │
│ square_logits ┆ claude-opus-5                   ┆ 0.277775           ┆ null       ┆ 31       │
└───────────────┴─────────────────────────────────┴────────────────────┴────────────┴──────────┘

In [19]:
import os
os.getcwd()

'c:\\Users\\User\\Documents\\Coding\\robot-chess-commentator\\evaluation'

## Hypothesis tests and confidence intervals

In [20]:
# 1. Identify the strongest CNN-based approach, and the strongest Claude-based approach
df.head()
cnn = (
    df.filter(pl.col("method").eq("cnn"), pl.col("split").eq("val"))
    .group_by("model_version", "prompt_version", "prior_correction")
    .agg(pl.col("correct_board_mean").mean())
    .sort("correct_board_mean", descending=True)
    .head(1)
)
claude = (
    df.filter(pl.col("method").ne("cnn"), pl.col("split").eq("val"))
    .group_by("method", "model_version", "prompt_version", "reasoning", "effort")
    .agg(pl.col("correct_board_mean").mean())
    .sort("correct_board_mean", descending=True)
    .head(1)
)
cnn, claude

(shape: (1, 4)
 ┌─────────────────────────────────┬────────────────┬──────────────────┬────────────────────┐
 │ model_version                   ┆ prompt_version ┆ prior_correction ┆ correct_board_mean │
 │ ---                             ┆ ---            ┆ ---              ┆ ---                │
 │ str                             ┆ i64            ┆ bool             ┆ f64                │
 ╞═════════════════════════════════╪════════════════╪══════════════════╪════════════════════╡
 │ optimised_plus_prior_correctio… ┆ 1              ┆ true             ┆ 0.947831           │
 └─────────────────────────────────┴────────────────┴──────────────────┴────────────────────┘,
 shape: (1, 6)
 ┌───────────────┬───────────────┬────────────────┬───────────┬────────┬────────────────────┐
 │ method        ┆ model_version ┆ prompt_version ┆ reasoning ┆ effort ┆ correct_board_mean │
 │ ---           ┆ ---           ┆ ---            ┆ ---       ┆ ---    ┆ ---                │
 │ str           ┆ str           ┆ i64            ┆ str       ┆ str    ┆ f64                │
 ╞═══════════════╪═══════════════╪════════════════╪═══════════╪════════╪════════════════════╡
 │ square_logits ┆ claude-opus-5 ┆ 1              ┆ thinking  ┆ low    ┆ 0.326845           │
 └───────────────┴───────────────┴────────────────┴───────────┴────────┴────────────────────┘)

In [21]:
cnn_rows = df.filter(pl.col("model_version").eq("optimised_plus_prior_correction"), pl.col("split").eq("test"))
claude_rows = df.filter(pl.col("model_version").eq("claude-opus-5"), pl.col("method").eq("square_logits"), pl.col("effort").eq("low"), pl.col("split").eq("test"))
cnn_rows, claude_rows

(shape: (11, 30)
 ┌────────┬─────────────┬────────────┬───────────┬───┬───────────┬────────────┬────────────┬────────┐
 │ method ┆ model_versi ┆ prompt_ver ┆ reasoning ┆ … ┆ cost_mean ┆ n_suggeste ┆ n_suggeste ┆ effort │
 │ ---    ┆ on          ┆ sion       ┆ ---       ┆   ┆ ---       ┆ d          ┆ d_mean     ┆ ---    │
 │ str    ┆ ---         ┆ ---        ┆ str       ┆   ┆ f64       ┆ ---        ┆ ---        ┆ str    │
 │        ┆ str         ┆ i64        ┆           ┆   ┆           ┆ str        ┆ str        ┆        │
 ╞════════╪═════════════╪════════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪════════╡
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │ cnn    ┆ optimised_p ┆ 1          ┆ none      ┆ … ┆ 0.0       ┆ null       ┆ null       ┆ high   │
 │        ┆ lus_prior_c ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 │        ┆ orrectio…   ┆            ┆           ┆   ┆           ┆            ┆            ┆        │
 └────────┴─────────────┴────────────┴───────────┴───┴───────────┴────────────┴────────────┴────────┘,
 shape: (11, 30)
 ┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
 │ method     ┆ model_vers ┆ prompt_ve ┆ reasoning ┆ … ┆ cost_mean ┆ n_suggest ┆ n_suggest ┆ effort │
 │ ---        ┆ ion        ┆ rsion     ┆ ---       ┆   ┆ ---       ┆ ed        ┆ ed_mean   ┆ ---    │
 │ str        ┆ ---        ┆ ---       ┆ str       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ str    │
 │            ┆ str        ┆ i64       ┆           ┆   ┆           ┆ str       ┆ str       ┆        │
 ╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.202691  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.202756  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.199876  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.2032475 ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.203038  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.201617  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.204188  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.203465  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.209023  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null]     ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.206376  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null]     ┆           ┆        │
 │ square_log ┆ claude-opu ┆ 1         ┆ thinking  ┆ … ┆ 0.205286  ┆ [null,    ┆ null      ┆ low    │
 │ its        ┆ s-5        ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,     ┆           ┆        │
 │            ┆            ┆           ┆           ┆   ┆           ┆ null,…    ┆           ┆        │
 └────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘)

In [22]:
cnn_rows["correct_board_mean"].mean(), claude_rows["correct_board_mean"].mean()

(0.9458874458874459, 0.22665945165945162)

In [23]:
import numpy as np
def bootstrap_ci(values: np.ndarray, B=10000, alpha=0.05, method="percentile"):
    point_estimate = values.mean()

    # 10000 times: subsample new arrays
    samples = np.random.choice(values, size=(B, values.size))

    estimates = samples.mean(axis=1)
    lower_q, upper_q = np.quantile(estimates, q=[alpha/2, 1 - alpha/2])

    if method != "percentile":
        return 2 * point_estimate - upper_q, 2 * point_estimate - lower_q
    return lower_q, upper_q

In [24]:
# Reason for percentile bootstrap interval: guaranteed to remain between 0 and 1
cnn_accuracies = cnn_rows["correct_board_mean"].to_numpy()
claude_accuracies = claude_rows["correct_board_mean"].to_numpy()
print(bootstrap_ci(cnn_accuracies))
print(bootstrap_ci(claude_accuracies))

(np.float64(0.8830627705627704), np.float64(1.0))
(np.float64(0.13383838383838384), np.float64(0.31919913419913415))

In [25]:
# Hypothesis test
n_cnn_better = 0
results = {}
for setup in cnn_rows["setup_id"].to_list():
    results[setup] = {
        "cnn_acc": cnn_rows.filter(pl.col("setup_id").eq(setup))["correct_board_mean"].item(),
        "claude_acc": claude_rows.filter(pl.col("setup_id").eq(setup))["correct_board_mean"].item()
    }
    results[setup]["d"] = results[setup]["cnn_acc"] - results[setup]["claude_acc"]
    if results[setup]["d"] > 0:
        n_cnn_better += 1

test_stat = n_cnn_better / len(results)

In [26]:
# p-value
# reference distrbution

In [27]:
import scipy.stats as stats

n = len(results)
as_extreme = []

for i in range(n + 1):
    if np.abs(i / n - 0.5) >= np.abs(test_stat - 0.5):
        as_extreme.append(i) 

p_val = stats.Binomial(n=n, p=0.5).pmf(as_extreme).sum()
p_val
#stats.Binomial(n=11, p=0.5).pmf([0, 1])

np.float64(0.0009765625)

In [28]:
# Plot distribution of test statistic
proportions = []
probs = []
bin = stats.Binomial(n=n, p=0.5)
for i in range(n + 1):
    proportions.append(i / n)
    probs.append(bin.pmf(i))

pl.DataFrame({"test_stat": proportions, "prob": probs}).write_csv("test_distribution.csv")

In [29]:
2 / 2**11

0.0009765625